[build]
  publish = ".next"
  command = "npm install && npm run build"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Netlify Functions configuration for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Redirect rules for authentication
[[redirects]]
  from = "/*"
  to = "/login"
  status = 302
  conditions = {Cookie = "!auth-token"}
  except = ["/login", "/api/auth/*", "/_next/*", "/favicon.ico"]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
